### ISSUE TITLE
how to get theme to work

### ISSUE THREAD

**Issue by batmanm0b1E** [actionless/awesome_config#23]
themes/lcars-xresourecs-hidpi/theme.lua 
unable to do so can you help

mine looks like this

https://i.imgur.com/j6rbHRw.png

**Comment by actionless** [comment]
it seems like you doesn't have any terminal colorscheme defined in your ~/.Xresources or doesn't have xrdb server initiated with that config.

that awesome theme is called `xresources` because it's using that colroscheme instead of hardcoded colors

you can download such colorschemes here:
 - http://dotshare.it/category/terms/colors/
 - https://terminal.sexy/
 - https://github.com/actionless/oomox/tree/master/oomox_gui/terminal_templates


the one used on screenshots in readme is:
http://dotshare.it/dots/873/

**Comment by batmanm0b1E** [comment]
OK Thank you have been most helpful try my best fix
